# Generated by Django 4.0.4 on 2022-05-07 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akabiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Akabiro', models.CharField(max_length=50)),
                ('Omubala', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Akabiro',
                'verbose_name_plural': 'Akabiro',
            },
        ),
        migrations.CreateModel(
            name='Kika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kika', models.CharField(max_length=50)),
                ('Owakasolya', models.CharField(max_length=50)),
                ('Asangibwa', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'kika',
                'verbose_name_plural': 'kika',
            },
        ),
        migrations.CreateModel(
            name='Lugya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lugya', models.CharField(max_length=50)),
                ('Lusangibwa', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Lugya',
                'verbose_name_plural': 'Lugya',
            },
        ),
        migrations.CreateModel(
            name='Lunyiriri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lunyiriri', models.CharField(max_length=50)),
                ('Owolunyiriri', models.CharField(max_length=50)),
                ('Asangibwa', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Lunyiriri',
                'verbose_name_plural': 'Lunyiriri',
            },
        ),
        migrations.CreateModel(
            name='Mutuba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mutuba', models.CharField(max_length=50)),
                ('Owomutuba', models.CharField(max_length=50)),
                ('Asangibwa', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Mutuba',
                'verbose_name_plural': 'Mutuba',
            },
        ),
        migrations.CreateModel(
            name='Siga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Siga', models.CharField(max_length=50)),
                ('Owesiga', models.CharField(max_length=50)),
                ('Asangibwa', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Siga',
                'verbose_name_plural': 'Siga',
            },
        ),
        migrations.CreateModel(
            name='Nju',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nju', models.CharField(max_length=50)),
                ('Esangibwa', models.CharField(max_length=50)),
                ('name', models.IntegerField(verbose_name='Generation')),
                ('desc_gen', models.CharField(max_length=200, verbose_name='Generation Description')),
                ('Lugya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Lugya_name', to='lineage.lugya')),
            ],
            options={
                'verbose_name': 'Nju',
                'verbose_name_plural': 'Nju',
            },
        ),
        migrations.CreateModel(
            name='Muganda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Erinya(Full Names)')),
                ('your_Life_Status', models.CharField(choices=[('Died', 'Died'), ('Living', 'Living')], max_length=100)),
                ('father', models.CharField(max_length=100, verbose_name='Taata(Father Full Name)')),
                ('father_Life_Status', models.CharField(choices=[('Died', 'Died'), ('Living', 'Living')], default='Living', max_length=100)),
                ('Address', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('Age', models.CharField(choices=[('Below 18', 'Below 18'), ('Above 18', 'Above 18')], max_length=50)),
                ('photo', models.ImageField(upload_to='pic')),
                ('Akabiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kika_name', to='lineage.akabiro')),
                ('Kika', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kika_name', to='lineage.kika')),
                ('Lugya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lugya_name', to='lineage.lugya')),
                ('Lunyiriri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lunyiriri_name', to='lineage.lunyiriri')),
                ('Mutuba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mutuba_name', to='lineage.mutuba')),
                ('Nju', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Nju_name', to='lineage.nju')),
                ('Siga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siga_name', to='lineage.siga')),
            ],
            options={
                'verbose_name': 'name',
                'verbose_name_plural': 'name',
            },
        ),
    ]
