# Generated by Django 4.0.4 on 2022-05-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineage', '0002_remove_muganda_age_muganda_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='muganda',
            options={'verbose_name': 'Muganda', 'verbose_name_plural': 'Muganda'},
        ),
    ]
